#!/usr/bin/env bash
# Update the package list to ensure we have the latest package information.
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start
