#!/usr/bin/env bash
# Update the package list and install nginx
apt-get update
apt-get install -y nginx

# Create a simple HTML page
cat << EOF > /var/www/html/index.html
<!DOCTYPE html>
<html>
<head>
<title>Hello World!</title>
</head>
<body>
<h1>Hello World!</h1>
</body>
</html>
EOF

# Make sure nginx is listening on port 80
sudo service nginx restart
