#!/usr/bin/env bash
# Update package index and install nginx with -y flag for automatic "Yes" responses
sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html
service nginx start
