#!/usr/bin/env bash
# Install Nginx if not already installed
if ! dpkg -l | grep -q nginx; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Define the custom header
custom_header="add_header X-Served-By \$hostname;"

# Configure Nginx to add the custom header
echo "Configuring Nginx..."
echo "$custom_header" | sudo tee /etc/nginx/conf.d/01-custom-header.conf

# Restart Nginx to apply the changes
sudo systemctl restart nginx

# Ignore shellcheck SC2154 warning for $hostname
# shellcheck disable=SC2154
