#!/usr/bin/env bash

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Configure custom Nginx response header
echo 'server {
    listen 80 default_server;
    server_name _;
    add_header X-Served-By $HOSTNAME;
    location / {
        proxy_pass http://localhost:80;
    }
}' | sudo tee /etc/nginx/sites-available/default > /dev/null

# Reload Nginx to apply the changes
sudo service nginx reload

# Ignore ShellCheck SC2154 warning
# shellcheck disable=SC2154
