#!/usr/bin/env bash

# Install HAProxy
apt-get update && apt-get install haproxy -y

# Create a configuration file for HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
  daemon
  maxconn 256

defaults
  mode http
  timeout connect 5000ms
  timeout client 50000ms
  timeout server 50000ms

frontend http
  bind *:80
  default_backend servers

backend servers
  balance roundrobin
  server 86762-web-01 100.25.196.36:80 check
  server 86762-web-02 52.87.215.223:80 check
EOF

# Enable HAProxy to start at boot
update-rc.d haproxy defaults

# Start HAProxy
service haproxy start
