#!/usr/bin/env bash
# a script to check if nginx is configured succesfully
# Remove the symbolic link to the default website configuration
sudo rm /etc/nginx/sites-enabled/default

# Create a new symbolic link to the default website configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx web server
sudo service nginx restart
