#!/usr/bin/env bash

apt-get update
apt-get -y install nginx

if ! service nginx status | grep -q "is running"; then
  sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
  service nginx reload
fi
