#!/usr/bin/env bash

# shellcheck disable=SC2009

# Script that displays lines containing the word "bash" and gets the PID of your Bash process
ps -ef | grep bash | grep -v "grep bash" | grep -v "$$"
