#!/usr/bin/env bash
# This script displays "bad luck" on the fourth line and "good luck" on the eighth line, along with "Best School" on other lines

counter=1
while [ $counter -le 10 ]
do
  if [ $counter -eq 4 ]
  then
    echo "Best School"
    echo "bad luck"
  elif [ $counter -eq 8 ]
  then
    echo "good luck"
  else 
    echo "Best School"
  fi

  ((counter++))
done
