#!/usr/bin/env bash
# Backup the original hosts file

sudo cp /etc/hosts /etc/hosts.bak
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts
sudo systemd-resolve --flush-caches
echo "Configuration completed. Localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8."
