#!/usr/bin/env bash
# This script configures and starts the Apache server in a Docker container

#import sub
import subprocess

# Configure Apache server
with open('/etc/apache2.conf', 'a') as apache_conf:
    apache_conf.write("ServerName localhost\n")

# Start Apache service
subprocess.run(['service', 'apache2', 'start'])
