#!/usr/bin/env bash
chmod 644 /etc/nginx/nginx.conf
sed -i 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen \(\[::\]:\)\?80 /listen 80 /' /etc/nginx/sites-enabled/default
service apache2 stop
sudo -u nginx service nginx restart
