#!/usr/bin/env bash
private_key_name="school"
key_bits=4096
# Generate the key pair
ssh-keygen -t rsa -b $key_bits -f $private_key_name
# Add passphrase to the private key
openssl rsa -aes256 -in "$private_key_name" -out "${private_key_name}_encrypted" -passout pass:betty
# Remove the unencrypted private key
rm "$private_key_name"
echo "RSA key pair has been created:"
ls -l "$private_key_name"*
